// webapp/src/App.vue
<script setup lang="ts">
import Controls from './components/Controls.vue'
import Output from './components/Output.vue'
import { reactive } from 'vue';
//@ts-ignore
import { getEngine, Input } from '@engine/main.ts';
//@ts-ignore
import { Engine } from '@engine/engine.ts'
//@ts-ignore
import { OutputConsumer, OutputMessage } from '@engine/messages/output.ts'
//@ts-ignore
import { IdValue } from '@engine/shared.ts'

fetch('./adventure.yaml')
  .then((response) => response.text())
  .then(data => {
    load(data);
    start();
    getStatus();
    getWords([]);
    console.log("Loaded!");
  })

const output : OutputMessage[] = [];
const engine : Engine = getEngine((message: OutputMessage) => output.push(message));

const state = reactive({ 
  command : [] as IdValue[],
  words : [] as IdValue[],
  text : [] as string[],
  status : ""
  });

function wordSelected(word: IdValue<string>) {
  state.command.push(word);
  getWords(state.command.map(word => word.id));
}

function execute() {
  engine.send(Input.execute(state.command.map(word => word.id)));
  state.text.push("> " + state.command.map(word => word.value).join(" "));
  if (output.length) {
    const values = output.map(message => message.value);
    values.forEach(value => state.text.push(value));
    output.length = 0;
  }
  state.command = [];
  getWords([]);
  getStatus();
}

function getWords(command : string[]) {
  engine.send(Input.getNextWords(command));
  for(const message of output) {
    if (message.type === "Words") {
      state.words = message.words;
    }
  }
  output.length = 0;
}

function getStatus() {
  engine.send(Input.getStatus());
  for(const message of output) {
    if (message.type === "Status") {
      state.status = message.status;
    }
  }
  output.length = 0;
}

function load(data : string) {
  engine.send(Input.load(data));
}

function start() {
  engine.send(Input.start());
}

</script>

<template>
    <div id="mainFrame">
      <div id="outputArea">
         <Output :text="state.text" :status="state.status" :command="state.command"/>
      </div>
      <div id="inputArea">
        <Controls
            :command="state.command"
            :words="state.words"
            @wordSelected="wordSelected"
            @execute="execute"/>
      </div>
    </div>
</template>

<style>
@import './assets/base.css';

#outputArea {
  position: relative;
  height: 70%;
  border: 2px solid blue;
}

#inputArea {
  position: relative;
  height: 30%;
  border: 2px solid red;
}

#mainFrame {
  height: 100vh;
  overflow: hidden;
}

</style>

// react-app/src/App.tsx
import { useRef, useState, useEffect } from 'react';
import './App.css';
import { getEngine, Input, createEngineProxy, createCommandFilter } from "tift-engine"
import { Engine } from "tift-engine/src/engine";
import { IdValue } from "tift-engine/src/shared";
import { OutputConsumer, OutputMessage } from "tift-engine/src/messages/output";
import { MessageForwarder } from "tift-engine/src/engineproxy";
import Output from "./components/Output"
import Controls from './components/Controls';
import { commandEntry, logEntry, LogLevel, messageEntry, OutputEntry } from './outputentry';

const GAME_FILE = "adventure.yaml";
//const GAME_FILE = "example.yaml";
const AUTO_SAVE = "TIFT_AUTO_SAVE";

function App() {
  const [command, setCommand] = useState<IdValue<string>[]>([]);
  const [words, setWords] = useState<IdValue<string>[]>([]);
  const [status, setStatus] = useState<string>("");

  // Store messages as a ref, as the can be updated multiple times between renders
  // and using a state makes it tricky to get the most up to date values
  const messagesRef = useRef<OutputEntry[]>([]);

  const engineRef = useRef<Engine | null>(null)

  const getWords = (command : IdValue<string>[]) => engineRef.current?.send(Input.getNextWords(command.map(word => word.id)));
  const execute = (command : IdValue<string>[]) => engineRef.current?.send(Input.execute(command.map(word => word.id)));

  const gameRestarter = (forwarder : MessageForwarder) =>  {
          fetch(process.env.PUBLIC_URL + "/" + GAME_FILE)
            .then((response) => response.text())
            .then(data => {
              console.log("Restarting");
              forwarder.send(Input.reset());
              forwarder.send(Input.load(data));
              forwarder.send(Input.config({"autoLook" : true}));
              forwarder.send(Input.start());
              getWords([]);
              forwarder.send(Input.getStatus());
            })
  }

  // Load a game file from the `public` folder
  const loadGame = (name : string, engine : Engine, saveData : string | null) => 
          fetch(process.env.PUBLIC_URL + "/" + name)
            .then((response) => response.text())
            .then(data => {
              if (engine == null) {
                throw new Error("Engine has not been initialized");
              }
              engine.send(Input.load(data));
              engine.send(Input.config({"autoLook" : true}));
              console.log("Loading: " + saveData);
              engine.send(Input.start((saveData != null)? saveData : undefined));
              getWords([]);
              engine.send(Input.getStatus());
            })

  // Initialization
  useEffect(() => {
    if (engineRef.current !== null) {
      return;
    }

    const saveGame = (saveData : string) => {
      console.log("Saving: " + saveData);
      window.localStorage.setItem(AUTO_SAVE, saveData);
    }

    messagesRef.current = [];
    const outputConsumer = getOutputConsumer(
      message => messagesRef.current?.push(messageEntry(message)),
      words => setWords(words),
      status => setStatus(status),
      (level, message) => messagesRef.current?.push(logEntry(level, message)),
      saveGame
    );
    const engine = createEngineProxy((output : OutputConsumer) => getEngine(output))
                      .insertProxy("restartFilter", createCommandFilter("restart", gameRestarter));
    engine.setResponseListener(outputConsumer);

    engineRef.current = engine;
    const saveData = window.localStorage.getItem(AUTO_SAVE);

    loadGame(GAME_FILE, engine, saveData);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // words updated
  useEffect(() => {
    const engine = engineRef.current;
    if (engine && command.length && !words.length) {
      messagesRef.current?.push(commandEntry(command.map(word => word.value).join(" ")))
      execute(command);
      engine.send(Input.getStatus());
      setCommand([]);
      getWords([]);
    }
  }, [words, command]);

  // command updated
  useEffect(() => {
    const engine = engineRef.current;
    if (engine) {
      getWords(command);
    }
  }, [command])

  return (
    <div className="App">
      <div className="mainFrame">
        <div className="outputArea">
          <Output entries={messagesRef.current ?? []} status={status} command={command.map(word => word.value).join(" ")}/>
        </div>
        <div id="inputArea" className="inputArea">
          <Controls words={words ?? []} wordSelected={(event,word) => setCommand([...command, word])}/>
        </div>
      </div>
    </div>
  );
}

function getOutputConsumer(messageConsumer : (message : string) => void,
                           wordsConsumer : (words : IdValue<string>[]) => void,
                           statusConsumer : (status : string) => void,
                           logConsumer : (level : LogLevel, message : string) => void,
                           saveConsumer : (saveData : string) => void) : (outputMessage : OutputMessage) => void {
  return (outputMessage) => {
    switch(outputMessage.type) {
      case "Print":
        messageConsumer(outputMessage.value);
        break;
      case "Words":
        wordsConsumer(outputMessage.words);
        break;
      case "Status":
        statusConsumer(outputMessage.status);
        break;
      case "SaveState": 
        saveConsumer(JSON.stringify(outputMessage.state));
        break;
      case "Log":
        logConsumer(outputMessage.level, outputMessage.message);
        break;
      default:
        throw new Error("Unsupported OutputMessage Type: " + outputMessage.type);
    }
  }
}

export default App;
